spring.application.name: nasa-asteroid-information-service
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "info"
  info:
    java:
      enabled: true

com:
  ka:
    nasa:
      lookup:
        api-name: "Nasa Asteroid Lookup Service"
        api-url: "https://api.nasa.gov/neo/rest/v1/neo/"
        api-key: "iM3ilYzTcgfwmFefCqwaqVzpncBkkcPHDc8ACqXG" #insert your own token here
      dates:
        api-name: "Nasa Asteroid Lookup Service for certain dates"
        api-url: "https://api.nasa.gov/neo/rest/v1/feed"
        api-key: "iM3ilYzTcgfwmFefCqwaqVzpncBkkcPHDc8ACqXG" #insert your own token here